### ISSUE TITLE
about test demo

### ISSUE THREAD

**Issue by tangyibo123** [lelechen63/Talking-head-Generation-with-Rhythmic-Head-Motion#7]
@lelechen63 @rainingDesert Thanks for your code. When I test my own video, the output information is only
`network loaded from `./checkpoints/face8_vox_new/latest_net_G.pth`
`model` [Vid2VidModel] was `created`
`after`0`   Then stop running，and no file is generated. 
I checked test_demo_ani.py, maybe there is a problem here,
`print(‘after {}'.format(len(pick_ids)))
`pick_ids = pick_ids[:opt.how_many]`
`for pick_id in pick_ids:`
`    paths = pickle_data[pick_id]`

`    print(‘process {} ....’format(pick_id))`
`   audio_tgt_path = get_param(pickle_data, pick_id, opt)`

Could you please tell me what to do?

**Comment by tangyibo123** [comment]
I have solved it. The reason is vox_demo_ani.npy. The file name recorded in this file needs to be consistent with the picture number in the demo. I want to know at which step this file was generated. Does anyone know?

**Comment by lelechen63** [comment]
> I have solved it. The reason is vox_demo_ani.npy. The file name recorded in this file needs to be consistent with the picture number in the demo. I want to know at which step this file was generated. Does anyone know?

Check the data folder.
